#!/bin/bash

PATCH="baselayout-usr-merge.patch"
for i in sys-apps/baselayout/baselayout-*.ebuild; do
	cat > ${PATCH} << EOF
--- a/${i}	2013-07-28 01:01:32.000000000 +0200
+++ b/${i}	2013-10-03 19:18:09.076757264 +0200
@@ -124,6 +124,34 @@
 	done
 }
 
+usrmerge_layout() {
+	local d
+	for d in bin sbin \$(get_all_libdirs) ; do
+		if [ -h "\${ROOT}\${d}" ] ; then
+			continue
+		elif [ -d "\${ROOT}\${d}" ] ; then
+			if [ -h "\${ROOT}usr/\${d}" ] ; then
+				if [ "\${SYMLINK_LIB}" = "yes" ] && [ "\${d}" == "lib" ] ; then
+					mv \${ROOT}\${d}/* \${ROOT}usr/\${d}/
+					rmdir \${ROOT}\${d}
+				else
+					die "\${ROOT}usr/\${d} is not a directory"
+				fi
+			elif [ -d "\${ROOT}usr/\${d}" ] ; then
+				# it is pointless to check for duplicate files
+				# if they don't exist everything is fine
+				# if they do they will reappear on first update
+				mv \${ROOT}\${d}/* \${ROOT}usr/\${d}/
+				rmdir \${ROOT}\${d}
+			else
+				mv \${ROOT}\${d} \${ROOT}usr/
+			fi
+		fi
+		ln -s usr/\${d} \${ROOT}\${d}
+		mkdir -p \${ROOT}usr/\${d}
+	done
+}
+
 pkg_preinst() {
 	# Bug #217848 - Since the remap_dns_vars() called by pkg_preinst() of
 	# the baselayout-1.x ebuild copies all the real configs from the user's
@@ -141,6 +169,7 @@
 	# stages, but they cannot be in CONTENTS.
 	# Also, we cannot reference \$S as binpkg will break so we do this.
 	multilib_layout
+	usrmerge_layout
 	if use build ; then
 		emake -C "\${D}/usr/share/\${PN}" DESTDIR="\${ROOT}" layout || die
 	fi
EOF
	git apply ${PATCH} || exit 1
	sed -i 's|,\(usr/,usr/local/\)|\1|' $i
	rm ${PATCH}
done
