#!/bin/sh

PATCH="rsync-hurd.patch"
for i in net-misc/rsync/rsync-3.1.2*.ebuild ; do
	cat > ${PATCH} << EOF
--- a/${i}
+++ b/${i}
@@ -28,6 +28,13 @@
 
 S=\${WORKDIR}/\${P/_/}
 
+src_prepare() {
+	sed -i 's/\*linux\*|\*netbsd\*/&|*gnu*/' configure.ac || die
+	sed -i 's/\*linux\*|\*netbsd\*/&|*gnu*/' configure.sh || die
+	touch config.h.in || die
+	default
+}
+
 src_configure() {
 	use static && append-ldflags -static
 	econf \\
EOF
	git apply ${PATCH} || exit 1
	rm ${PATCH}
done
for i in net-misc/rsync/rsync-3.1.3*.ebuild ; do
	cat > ${PATCH} << EOF
--- a/${i}
+++ b/${i}
@@ -28,6 +28,13 @@
 
 S="\${WORKDIR}/\${P/_/}"
 
+src_prepare() {
+	sed -i 's/\*linux\*|\*netbsd\*/&|*gnu*/' configure.ac || die
+	sed -i 's/\*linux\*|\*netbsd\*/&|*gnu*/' configure.sh || die
+	touch config.h.in || die
+	default
+}
+
 src_configure() {
 	use static && append-ldflags -static
 	local myeconfargs=(
EOF
	git apply ${PATCH} || exit 1
	rm ${PATCH}
done
